Repository FESI-FlowIt/Frontend, pull requests merged in 2025-08, with the labels that each got.

#192 [Fix:#182] 인증/인가 관련 Next middleware.ts 작성
  middleware.ts
  src/api/apiWrapper.ts
  src/api/index.ts
  src/api/refreshAccessToken.ts
  src/app/api/logout/route.ts
  src/app/layout.tsx
  src/app/providers/AuthProvider.tsx
  src/components/auth/LoginForm.tsx
  src/hooks/auth/useLogin.ts
  src/hooks/auth/useLogout.ts
  src/lib/cookies.ts
  src/middleware.ts
  src/store/authStore.ts
Labels: Completed, infra

#204 [Fix/#202] 인증/인가 로직 수정
  src/api/apiWrapper.ts
  src/api/authApi.ts
  src/api/refreshAccessToken.ts
  src/app/api/logout/route.ts
Labels: Completed

#208 [fix/#205] 대시보드 목표별 할일 스토리북 오류 수정
  src/stories/goals/GoalListDashboardCard.stories.tsx
Labels: Completed

#212 [Fix/#196] 공통 Popover 컴포넌트 개선
  src/components/heatmaps/HeatmapSection.tsx
  src/components/ui/Popover.tsx
Labels: enhancement, Completed

#215 [Refactor/#213] 팝오버 위치 계산 로직을 재사용 가능한 유틸리티로 분리
  src/components/calendar/CalendarSection.tsx
  src/components/heatmaps/HeatmapSection.tsx
  src/hooks/usePopover.ts
  src/interfaces/popover.ts
  src/lib/popover.ts
Labels: Completed

#225 [Style/#198] 랜딩페이지의 이미지 교체 및 순서 수정
  public/assets/images/landing_heatmap-detail.svg
  public/assets/images/landing_todos-detail.svg
  src/components/landing/LandingFeaturesDetail.tsx
  src/components/landing/LandingIntroduction.tsx
  src/constants/landingPageFeatures.ts
Labels: Completed

#229 [Feat/#177] 노트 모아보기 UI 구현
  src/assets/icons/arrow-down-full.svg
  src/components/notes/NotesClient.tsx
  src/components/notes/TodoWithNoteItem.tsx
  src/components/notes/TodoWithNoteList.tsx
  src/components/notes/constants.ts
  src/components/todos/GoalSelector.tsx
  src/interfaces/todo.ts
Labels: enhancement, Completed

#230 [Style/#226] 랜딩페이지 반응형 디자인 수정
  src/components/landing/LandingBanner.tsx
  src/components/landing/LandingFeaturesDetail.tsx
  src/components/landing/LandingIntroduction.tsx
  src/lib/cn.ts
  src/styles/globals.css
Labels: Completed

#233 [Style/#224] 사이드바 반응형 디자인 수정 및 hover 설정
  src/app/(main)/layout.tsx
  src/components/sidebar/Sidebar.tsx
  src/components/sidebar/SidebarGoalsList.tsx
  src/components/sidebar/SidebarMenu.tsx
  src/components/sidebar/SidebarUser.tsx
  src/lib/cn.ts
  src/styles/globals.css
Labels: Completed

#236 [Feat/#227] notesidebar UI 구현
  src/assets/icons/pencil.svg
  src/components/notes/NoteContentEditor.tsx
  src/components/notes/NoteInfo.tsx
  src/components/notes/constants.ts
  src/components/ui/Button.tsx
  src/components/ui/NoteSidebar/NoteDetailEditMode.tsx
  src/components/ui/NoteSidebar/NoteDetailReadMode.tsx
  src/components/ui/NoteSidebar/NoteDetailSidebar.tsx
  src/components/ui/NoteSidebar/NoteListSidebar.tsx
  src/components/ui/NoteSidebar/NoteSidebar.tsx
  src/interfaces/todo.ts
  src/stories/ui/NoteSidebar.stories.tsx
Labels: enhancement, Completed

#234 [Test/#193] 공통 Button 컴포넌트 테스트 코드 작성
  eslint.config.mjs
  package-lock.json
  package.json
  src/tests/ui/Button.test.tsx
  tests/example.test.ts
  tsconfig.json
Labels: Completed

#241 [Test/#238] EmailInput 컴포넌트에 대한 테스트 코드 작성
  src/tests/auth/EmailInput.test.tsx
Labels: Completed

#244 [Feat/#178] 노트 모아보기 및 노트 사이드바 기능 구현
  src/api/mapper/noteMapper.ts
  src/api/notesApi.ts
  src/components/notes/NotesClient.tsx
  src/components/notes/TodoWithNoteItem.tsx
  src/components/notes/TodoWithNoteList.tsx
  src/components/notes/constants.ts
  src/components/ui/NoteSidebar/NoteDetailSidebar.tsx
  src/components/ui/NoteSidebar/NoteListSidebar.tsx
  src/components/ui/NoteSidebar/NoteSidebar.tsx
  src/hooks/useNotes.ts
  src/hooks/useTempNote.ts
  src/interfaces/note.ts
  src/interfaces/todo.ts
  src/lib/actions/tempNotes.ts
  src/mocks/handlers/noteHandlers.ts
  src/mocks/mockResponses/notes/noteDetailsResponse.ts
  src/mocks/mockResponses/notes/todosWithNoteResponse.ts
  src/stories/ui/NoteSidebar.stories.tsx
Labels: enhancement, Completed

#232 [Feat/#201] 일정관리표 api 연동
  src/api/mapper/scheduleMapper.ts
  src/api/scheduleApi.ts
  src/components/schedule/ScheduleFooter.tsx
  src/components/schedule/ScheduleModal.tsx
  src/components/schedule/ScheduleSection.tsx
  src/components/schedule/TimeSlotRow.tsx
  src/components/schedule/TimeTable.tsx
  src/components/schedule/UnassignedTaskList.tsx
  src/components/timer/EmptyTodoGuide.tsx
  src/components/timer/SelectTodoModal.tsx
  src/components/timer/SelectTodoModalBody.tsx
  src/components/timer/SelectTodoModalEmpty.tsx
  src/components/timer/SelectTodoModalHeader.tsx
  src/hooks/useSchedule.ts
  src/interfaces/schedule.ts
  src/lib/dayjs.ts
  src/lib/format.ts
Labels: Completed

#247 [Feat/#183] 카카오 소셜 로그인 연결
  src/api/authApi.ts
  src/app/oauth/callback/page.tsx
  src/components/auth/SocialLoginCard.tsx
  src/hooks/auth/useSocialLogin.ts
  src/middleware.ts
Labels: Completed

#257 [Style/#206] 히트맵 영역과 마감일 캘린더 영역의 반응형 디자인 작업
  src/app/(main)/dashboard/page.tsx
  src/app/(main)/layout.tsx
  src/components/calendar/CalendarCell.tsx
  src/components/calendar/CalendarGrid.tsx
  src/components/heatmaps/HeatmapCell.tsx
  src/components/heatmaps/HeatmapLayout.tsx
  src/components/heatmaps/HeatmapRow.tsx
  src/components/heatmaps/HeatmapSection.tsx
  src/components/insight/InsightCard.tsx
  src/components/ui/Card.tsx
Labels: Completed

#268 [Style/#262] 목표, 노트에 대한 반응형 수정
  src/components/goals/calendar/CalendarDropdown.tsx
  src/components/goals/goalDetail/GoalDetailClient.tsx
  src/components/goals/goalDetail/GoalDetailHeader.tsx
  src/components/goals/goalList/GoalCard.tsx
  src/components/goals/goalList/GoalsFilterControls.tsx
  src/components/goals/goalList/GoalsList.tsx
  src/components/goals/goalList/GoalsPagination.tsx
  src/components/notes/NoteToolbar.tsx
  src/components/notes/NoteWriteClient.tsx
Labels: enhancement, Completed

#264 [Refactor/#255] 히트맵 컴포넌트 고정 레이아웃 및 빈 상태 처리 구현
  src/components/heatmaps/HeatmapCell.tsx
  src/components/heatmaps/HeatmapLayout.tsx
  src/components/heatmaps/HeatmapRow.tsx
  src/components/heatmaps/HeatmapSection.tsx
  src/components/heatmaps/MonthlyHeatmap.tsx
  src/components/heatmaps/WeeklyHeatmap.tsx
  src/interfaces/heatmap.ts
  src/mocks/mockResponses/heatmap/monthlyHeatmapResponse.ts
Labels: Completed

#270 [Fix/#265] 토큰 갱신 에러 수정
  src/api/refreshAccessToken.ts
  src/middleware.ts
Labels: Completed

#276 [Feat/#203] 타이머 api 연동 및 반응형 디자인 수정
  src/api/mapper/timerMapper.ts
  src/api/timerApi.ts
  src/assets/icons/timer.svg
  src/components/timer/EmptyTodoGuide.tsx
  src/components/timer/SelectTodoModal.tsx
  src/components/timer/SelectTodoModalBody.tsx
  src/components/timer/SelectTodoModalHeader.tsx
  src/components/timer/TimerControls.tsx
  src/components/timer/TimerDisplay.tsx
  src/components/timer/TimerModal.tsx
  src/components/timer/TimerWidget.tsx
  src/components/timer/TotalTime.tsx
  src/components/timer/TotalTimerDisplay.tsx
  src/components/ui/Modal.tsx
  src/hooks/useTotalRunningTime.ts
  src/interfaces/timer.ts
  src/store/timerStore.ts
Labels: Completed

#279 [Feat/#278] 마감일 캘린더 에러 처리
  src/api/calendarApi.ts
  src/components/calendar/CalendarSection.tsx
  src/hooks/useGoalCalendar.ts
Labels: Completed

#282 [FEAT/#280] 시연을 위한 InsightCard 상태별 variant 추가
  src/components/heatmaps/HeatmapSection.tsx
  src/components/insight/InsightCard.tsx
  src/stories/insight/InsightCard.stories.tsx
Labels: Completed

#285 [FEAT/#267] 목표 할일 노트 에러 처리 (토스트)
  src/hooks/useGoals.ts
  src/hooks/useTempNote.ts
  src/hooks/useTodos.ts
Labels: enhancement, Completed

#289 [Feat/253] 노트 api 연결
  package-lock.json
  package.json
  src/api/goalsApi.ts
  src/api/index.ts
  src/api/mapper/noteMapper.ts
  src/api/mapper/todoMapper.ts
  src/api/notesApi.ts
  src/api/todosApi.ts
  src/app/(main)/goal/notes/page.tsx
  src/components/goals/GoalForm.tsx
  src/components/goals/GoalModal.tsx
  src/components/goals/goalDetail/GoalDetailClient.tsx
  src/components/notes/NoteWriteClient.tsx
  src/components/notes/NotesClient.tsx
  src/components/notes/TodoWithNoteItem.tsx
  src/components/todos/AttachmentUpload.tsx
  src/components/todos/LinkModal.tsx
  src/components/todos/TodoAttachmentIcons.tsx
  src/components/todos/TodoContent.tsx
  src/components/todos/TodoForm.tsx
  src/components/todos/TodoModal.tsx
  src/components/todos/TodoModalButton.tsx
  src/components/todos/TodoModals.tsx
  src/components/ui/Modal.tsx
  src/components/ui/NoteSidebar/NoteDetailSidebar.tsx
  src/components/ui/NoteSidebar/NoteListSidebar.tsx
  src/components/ui/NoteSidebar/NoteSidebar.tsx
  src/components/ui/Toast/ToastIcon.tsx
  src/hooks/useGoals.ts
  src/hooks/useNotes.ts
  src/hooks/useTodoForm.ts
  src/interfaces/note.ts
  src/interfaces/todo.ts
  src/lib/sanitizeUtil.ts
  src/mocks/handlers/goalHandlers.ts
  src/mocks/handlers/noteHandlers.ts
  src/mocks/mockResponses/notes/todosWithNoteResponse.ts
  src/store/todoAttachmentsStore.ts
  src/stories/ui/NoteSidebar.stories.tsx
Labels: enhancement, Completed

#300 [Fix/#206] 히트맵 새로고침 기능 추가, 캘린더 목표 표시 개선, 화살표 아이콘 스타일 수정
  src/components/calendar/CalendarCell.tsx
  src/components/ui/IconButton.tsx
  src/hooks/useHeatmap.ts
  src/hooks/useHeatmapsSection.ts
  src/styles/globals.css
Labels: Completed

#299 [FIX/#294] 시연전 마지막 에러 수정
  src/components/goals/goalDetail/GoalDetailHeader.tsx
  src/components/goals/goalList/GoalCard.tsx
  src/components/todos/TodoAttachmentIcons.tsx
  src/components/todos/TodoModal.tsx
  src/styles/globals.css
Labels: Completed

#302 [fix:/#301] 타이머 목표 조회 수정
  src/components/timer/TimerWidget.tsx
Labels: Completed
