Repository FESI-FlowIt/Frontend, pull requests merged in 2025-07, with the labels that each got.

#8 [Feat/#6] Storybook 자동 배포 CD
  .github/workflows/storybook-cd.yml
  package-lock.json
  package.json
  src/stories/Example.stories.tsx
Labels: Completed

#40 [Feat/#31] Logo 컴포넌트 제작
  .storybook/preview.ts
  public/assets/images/logoIcon.svg
  src/components/auth/Logo.tsx
  src/lib/routes.ts
  src/stories/auth/Logo.stories.tsx
  src/styles/globals.css
Labels: Completed

#39 [Feat/#30] Social login card 컴포넌트 제작
  .storybook/main.ts
  package-lock.json
  package.json
  public/assets/images/googleLogo.svg
  public/assets/images/kakaoLogo.svg
  public/assets/images/naverLogo.svg
  src/components/auth/SocialLoginCard.tsx
  src/components/auth/exampe.tsx
  src/stories/auth/SocialLoginCard.stories.tsx
Labels: Completed

#46 [Feat/#11] LoginForm 컴포넌트 제작 및 MSW 셋팅
  .prettierignore
  eslint.config.mjs
  jest.config.ts
  package-lock.json
  package.json
  public/assets/images/visibility_off.svg
  public/assets/images/visibility_on.svg
  public/mockServiceWorker.js
  src/app/layout.tsx
  src/app/providers/MswProvider.tsx
  src/components/auth/LoginForm.tsx
  src/components/ui/Input.tsx
  src/lib/validation.tsx
  src/mocks/browser.ts
  src/mocks/handlers.ts
  src/mocks/handlers/authHandlers.ts
  src/mocks/handlers/index.ts
  src/mocks/index.ts
  src/mocks/mockResponses/auth/loginResponse.ts
  src/mocks/server.ts
  src/stories/auth/LoginForm.stories.tsx
  vitest.setup.ts
Labels: Completed

#55 [Feat/#36] 회원가입 페이지 제작
  src/app/auth/signup/page.tsx
  src/components/auth/LoginForm.tsx
  src/components/auth/SignUpForm.tsx
  src/components/ui/Button.tsx
  src/components/ui/Input.tsx
  src/lib/validation.tsx
  src/mocks/handlers/authHandlers.ts
  src/stories/auth/SignUpForm.stories.tsx
Labels: Completed

#62 [Feat/#48] 대쉬보드 사이드바 헤더 컴포넌트 제작
  public/assets/icons/menu-left.svg
  src/components/sidebar/SidebarHeader.tsx
  src/styles/globals.css
Labels: Completed

#66 [Feat/#63] 대쉬보드 사이드바 유저 컴포넌트 제작
  src/components/sidebar/SidebarUser.tsx
  src/interfaces/auth.ts
  src/interfaces/exampleInterface.ts
  src/mocks/handlers/authHandlers.ts
  src/store/store.ts
  src/store/userStore.ts
  src/stories/Example.stories.tsx
Labels: Completed

#73 [Feat/#58] 공통 IconButton 컴포넌트 구현
  public/assets/icons/closeIcon.svg
  public/assets/icons/infoIcon.svg
  src/components/ui/IconButton.tsx
  src/stories/ui/IconButton.stories.tsx
Labels: enhancement

#74 [Feat/#52] 공통 Popover 컴포넌트 구현
  public/assets/icons/timerIcon.svg
  src/components/ui/Popover.tsx
  src/stories/ui/Popover.stories.tsx
Labels: enhancement

#80 [Feat/#67] 로그인 & 회원가입 실패 모달 제작
  src/components/auth/AuthModal.tsx
  src/components/auth/LoginForm.tsx
  src/components/auth/SignUpForm.tsx
  src/components/ui/Button.tsx
  src/components/ui/Modal.tsx
  src/lib/routes.ts
  src/stories/auth/AuthModal.stories.tsx
Labels: Completed

#54 [Feat#51] 공통컴포넌트 dialog 제작
  src/stories/ui/Dialog.stories.tsx
Labels: enhancement, Completed

#79 [Feat/#21] 작업 시간 분석 표인 주간, 월간 Heatmap 구현
  src/components/heatmaps/HeatmapCell.tsx
  src/components/heatmaps/HeatmapInfoPopover.tsx
  src/components/heatmaps/HeatmapLayout.tsx
  src/components/heatmaps/HeatmapRow.tsx
  src/components/heatmaps/LegendSection.tsx
  src/components/heatmaps/MonthlyHeatmap.tsx
  src/components/heatmaps/WeeklyHeatmap.tsx
  src/constants/heatmap.ts
  src/interfaces/heatmap.ts
  src/lib/format.ts
  src/mocks/mockResponses/heatmap/monthlyHeatmapResponse.ts
  src/mocks/mockResponses/heatmap/weeklyHeatmapResponse.ts
  src/stories/heatmap/HeatmapCell.stories.tsx
  src/stories/heatmap/HeatmapInfoPopover.stories.tsx
  src/stories/heatmap/MonthlyHeatmap.stories.tsx
  src/stories/heatmap/WeeklyHeatmap.stories.tsx
Labels: enhancement

#81 [Chore/#75] API wrapper 및 HTTP 메서드별 함수 캡슐화
  src/api/apiWrapper.ts
  src/api/example.ts
  src/api/index.ts
  src/store/authStore.ts
Labels: Completed

#86 [Refactor/#82] 로그인 페이지 비즈니스 로직 수정
  src/api/authApi.ts
  src/components/auth/LoginForm.tsx
  src/components/auth/SignUpForm.tsx
  src/hooks/auth/useLogin.ts
  src/hooks/example.ts
  src/interfaces/auth.ts
  src/lib/validation.tsx
Labels: Completed

#91 [Chore/#77] Pretendard 폰트 설정 및 포괄적 CSS Reset 구현
  package-lock.json
  package.json
  src/app/layout.tsx
  src/styles/globals.css
  src/styles/tailwind.config.ts
Labels: enhancement

#88 [Refactor/#83] 회원가입 페이지 비즈니스 로직 수정
  src/api/authApi.ts
  src/app/auth/signup/page.tsx
  src/components/auth/AuthModal.tsx
  src/components/auth/EmailInput.tsx
  src/components/auth/LoginForm.tsx
  src/components/auth/NameInput.tsx
  src/components/auth/PasswordInput.tsx
  src/components/auth/SignUpForm.tsx
  src/hooks/auth/useSignup.ts
  src/stories/auth/LoginForm.stories.tsx
  src/stories/auth/SignUpForm.stories.tsx
Labels: Completed

#105 [Feat/#94] 공통 ArrowNavigation 컴포넌트 구현
  public/assets/icons/nextIcon.svg
  public/assets/icons/prevIcon.svg
  src/components/ui/ArrowNavigation.tsx
  src/components/ui/IconButton.tsx
  src/stories/ui/ArrowNavigation.stories.tsx
  src/stories/ui/IconButton.stories.tsx
Labels: enhancement

#114 [Refactor/#110] 목표 관련 api 리팩토링
  src/api/goalsApi.ts
  src/api/index.ts
  src/hooks/useGoals.ts
  src/mocks/handlers/goalHandlers.ts
  src/mocks/handlers/todoHandlers.ts
  src/mocks/mockResponses/goals/goalsResponse.ts
  src/mocks/mockResponses/todos/todosResponse.ts
  src/mocks/utils/storage.ts
Labels: enhancement, Completed

#119 [Feat/#56] 랜딩페이지 베너 컴포넌트 제작
  public/assets/images/dashboard.svg
  public/assets/images/landing_img.svg
  src/components/landing/LandingBanner.tsx
  src/stories/landing/LandingBanner.stories.tsx
  src/styles/globals.css
Labels: Completed

#126 [Feat/#120] 랜딩페이지 소개 컴포넌트 제작
  public/assets/images/landing_calendar.svg
  public/assets/images/landing_goal.svg
  public/assets/images/landing_heatmap.svg
  public/assets/images/landing_img.svg
  public/assets/images/landing_timer.svg
  src/components/landing/LandingIntroduction.tsx
  src/constants/landingPageFeatures.ts
  src/stories/landing/LandingIntroduction.stories.tsx
Labels: Completed

#128 [Feat/#98] 목표별 마감일을 확인할 수 있는 CalendarSection 구현
  public/assets/icons/calendarIcon.svg
  src/api/calendarApi.ts
  src/components/calendar/CalendarCell.tsx
  src/components/calendar/CalendarSection.tsx
  src/components/heatmaps/HeatmapSection.tsx
  src/components/ui/ArrowNavigation.tsx
  src/components/ui/Card.tsx
  src/components/ui/IconButton.tsx
  src/hooks/useGoalCalendar.ts
  src/interfaces/calendar.ts
  src/lib/calendar.ts
  src/mocks/handlers/calendarHandlers.ts
  src/mocks/handlers/index.ts
  src/mocks/mockResponses/calendar/calendarResponse.ts
Labels: enhancement, Completed

#132 [Feat/#124] 랜딩페이지 기능 설명 컴포넌트 제작
  public/assets/images/landing_calendar-detail.svg
  public/assets/images/landing_goal-detail.svg
  public/assets/images/landing_heatmap-detail.svg
  public/assets/images/landing_timer-detail.svg
  public/assets/images/landing_todos-detail.svg
  src/components/landing/LandingFeaturesDetail.tsx
  src/constants/landingPageFeatures.ts
  src/stories/landing/LandingFeatruesDetail.stories.tsx
Labels: Completed

#133 [Feat/#99] 마감일캘린더 클릭 시 나오는 CalendarGoalPopover 컴포넌트 구현
  src/components/calendar/CalendarCell.tsx
  src/components/calendar/CalendarGoalPopover.tsx
  src/components/calendar/CalendarGrid.tsx
  src/components/calendar/CalendarSection.tsx
  src/components/ui/Popover.tsx
  src/lib/calendar.ts
  src/mocks/mockResponses/calendar/calendarResponse.ts
  src/stories/calendar/CalendarCell.stories.tsx
  src/stories/calendar/CalendarGoalPopover.stories.tsx
  src/stories/calendar/CalendarGrid.stories.tsx
  src/stories/ui/Popover.stories.tsx
Labels: Completed

#136 [Feat/#125] 랜딩페이지 UI 제작
  src/app/page.tsx
  src/components/landing/LandingBanner.tsx
  src/components/landing/LandingIntroduction.tsx
  src/constants/landingPageFeatures.ts
  src/styles/globals.css
Labels: Completed

#139 [Feat/#130] 로그인 및 회원가입 페이지 API 연결
  src/api/apiWrapper.ts
  src/api/authApi.ts
  src/components/auth/LoginForm.tsx
  src/components/auth/SignUpForm.tsx
  src/hooks/auth/useLogin.ts
  src/hooks/auth/useSignup.ts
  src/interfaces/auth.ts
Labels: Completed

#140 [Feat/#131] 대쉬보드 사이드바 API 연결
  src/api/sidebarApi.ts
  src/components/sidebar/SidebarGoalsList.tsx
  src/hooks/auth/useUser.ts
  src/hooks/useSidebar.ts
  src/interfaces/auth.ts
  src/interfaces/sidebar.ts
  src/lib/goalColorUtils.ts
Labels: Completed

#144 [Refactor:#143] - accessToken logic 수정
  src/api/apiWrapper.ts
  src/api/authApi.ts
Labels: Completed

#146 [Refactor/#129] 캘린더 백엔드 API 연동 및 데이터 매퍼 구현
  src/api/calendarApi.ts
  src/hooks/useGoalCalendar.ts
  src/interfaces/calendar.ts
  src/lib/calendarMapper.ts
  src/mocks/handlers/calendarHandlers.ts
Labels: Completed

#159 [Refactor/#106] 로그인 & 회원가입 페이지에 loading ui 적용
  src/components/auth/LoginForm.tsx
  src/components/auth/SignUpForm.tsx
  src/components/ui/CustomLoading.tsx
  src/stories/ui/CustomLoading.stories.tsx
  src/styles/globals.css
Labels: Completed

#156 [Feat/#111] 목표/ 할일 mapper 구현
  src/interfaces/goal.ts
  src/interfaces/todo.ts
  src/lib/goalMapper.ts
  src/lib/todoMapper.ts
Labels: enhancement, Completed

#168 [Refactor/#166] 시연 전 리팩토링
  src/api/sidebarApi.ts
  src/app/(main)/dashboard/page.tsx
  src/components/goals/goalList/GoalsHeader.tsx
  src/hooks/useGoalCalendar.ts
  src/hooks/useGoals.ts
  src/hooks/useSidebar.ts
Labels: enhancement, Completed

#169 [Chore/5] develop → main 병합 및 CI/CD 자동 배포
  src/api/dashboardGoalsApi.ts
  src/api/goalsApi.ts
  src/api/sidebarApi.ts
  src/api/todosApi.ts
  src/app/(main)/dashboard/page.tsx
  src/app/(main)/goal/[goalId]/page.tsx
  src/app/(main)/goal/page.tsx
  src/app/(main)/layout.tsx
  src/app/providers/SidebarProvider.tsx
  src/components/calendar/CalendarCell.tsx
  src/components/calendar/CalendarGoalPopover.tsx
  src/components/goals/GoalCardContent.tsx
  src/components/goals/GoalForm.tsx
  src/components/goals/GoalListDashboardCard.tsx
  src/components/goals/GoalListDashboardSection.tsx
  src/components/goals/NoGoalsGuide.tsx
  src/components/goals/goalDetail/GoalDetailClient.tsx
  src/components/goals/goalDetail/GoalDetailHeader.tsx
  src/components/goals/goalDetail/TodoSection.tsx
  src/components/goals/goalList/GoalCard.tsx
  src/components/goals/goalList/GoalsClientContent.tsx
  src/components/goals/goalList/GoalsHeader.tsx
  src/components/heatmaps/HeatmapSection.tsx
  src/components/schedule/ScheduleModal.tsx
  src/components/schedule/ScheduleSection.tsx
  src/components/sidebar/Sidebar.tsx
  src/components/sidebar/SidebarGoalsList.tsx
  src/components/sidebar/SidebarHeader.tsx
  src/components/timer/SelectTodoModal.tsx
  src/components/timer/TaskInfo.tsx
  src/components/timer/TimerControls.tsx
  src/components/timer/TimerWidget.tsx
  src/components/todos/GoalSelector.tsx
  src/components/todos/TodoModal.tsx
  src/components/ui/Card.tsx
  src/components/ui/Input.tsx
  src/hooks/useGoalCalendar.ts
  src/hooks/useGoals.ts
  src/hooks/useSidebar.ts
  src/hooks/useTodoForm.ts
  src/hooks/useTodos.ts
  src/interfaces/calendar.ts
  src/interfaces/goal.ts
  src/interfaces/note.ts
  src/interfaces/todo.ts
  src/lib/calendarMapper.ts
  src/lib/goalListDashboardMapper.ts
  src/lib/goalMapper.ts
  src/lib/routes.ts
  src/mocks/handlers/goalHandlers.ts
  src/mocks/handlers/todoHandlers.ts
  src/mocks/mockResponses/goals/goalsResponse.ts
  src/mocks/mockResponses/todos/todosResponse.ts
  src/store/modalStore.ts
  src/stories/goals/GoalModal.stories.tsx
  src/stories/schedule/SimpleScheduleCard.stories.tsx
  src/stories/timer/Widget.stories.tsx
  src/stories/todos/TodoModal.stories.tsx
Labels: infra

#173 [Chore/6] develop → main 병합 및 CI/CD 자동 배포
  src/app/providers/MswProvider.tsx
Labels: infra

#186 [Feat/#175] 노트 작성 페이지 UI 구현
  public/assets/icons/icAlignmentcenter.svg
  public/assets/icons/icAlignmentleft.svg
  public/assets/icons/icAlignmentright.svg
  public/assets/icons/icBullet.svg
  public/assets/icons/icbold.svg
  public/assets/icons/iccoloring.svg
  public/assets/icons/icitalic.svg
  public/assets/icons/icnumbering.svg
  public/assets/icons/icunderline.svg
  public/assets/icons/linkAlt.svg
  src/components/notes/NoteContentEditor.tsx
  src/components/notes/NoteHeader.tsx
  src/components/notes/NoteInfo.tsx
  src/components/notes/NoteToolbar.tsx
  src/components/notes/NoteWriteClient.tsx
  src/components/notes/exampe.tsx
  src/components/ui/Button.tsx
  src/components/ui/IconButton.tsx
  src/components/ui/Input.tsx
  src/constants/toolBarGroups.ts
Labels: enhancement, Completed

#185 [Style/#180] 랜딩페이지 반응형 디자인을 적용
  src/app/page.tsx
  src/components/landing/LandingBanner.tsx
  src/components/landing/LandingFeaturesDetail.tsx
  src/components/landing/LandingIntroduction.tsx
  src/styles/globals.css
Labels: enhancement, Completed

#189 [Chore/#188] favicon, og & twitter metadata 설정
  opengraph-image.png
  public/favicon.ico
  src/app/layout.tsx
  twitter-image.png
Labels: Completed
